### ISSUE TITLE
TF Layer conv2d doesn't support masking

### ISSUE THREAD

**Issue by natelee100** [ericperriard/scrappybara#14]
I am running into a TypeError: Layer conv2d does not support masking, but was passed an input_mask: Tensor("embedding/NotEqual:0", shape=(?, 52, 22), dtype=bool, device=/device:CPU:0)

It seems to be generated from this line inside 'syntax\models.py' line 37/38. 

conv = tf.keras.layers.Conv2D(self.__convolution_filters, (1, window), activation='relu', padding='same')(char_embed)
pools.append(tf.keras.layers.MaxPool2D(pool_size=(1, cfg.PADDED_WORD_LENGTH))(conv))

All I have done so far is 

import scrappybara as sb
pipe = sb.Pipeline()
Would love to know how to fix this.

Here is the full stacktrace:
Traceback (most recent call last):
  File "linking.py", line 10, in <module>
    pipe = sb.Pipeline()
  File "Programs\Python\Python37\lib\site-packages\scrappybara\pipeline\pipeline.py", line 33, in __init__
    self.__parse = Parser(self.__lm, 128)
  File "Programs\Python\Python37\lib\site-packages\scrappybara\syntax\parser.py", line 104, in __init__
    self.__ptags_model = PTagsModel(len(self.__charset)).load()
  File "Programs\Python\Python37\lib\site-packages\scrappybara\syntax\models.py", line 71, in __init__
    char_model = self._char_model(charset_size)
  File "Programs\Python\Python37\lib\site-packages\scrappybara\syntax\models.py", line 37, in _char_model
    conv = tf.keras.layers.Conv2D(self.__convolution_filters, (1, window), activation='relu', padding='same')(char_embed)
  File "Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 581, in __call__
    self._set_mask_metadata(inputs, outputs, previous_mask)
  File "Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1356, in _set_mask_metadata
    output_mask = self.compute_mask(inputs, previous_mask)
  File "Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 473, in compute_mask
    'but was passed an input_mask: ' + str(mask))
TypeError: Layer conv2d does not support masking, but was passed an input_mask: Tensor("embedding/NotEqual:0", shape=(?, 52, 22), dtype=bool, device=/device:CPU:0)

**Comment by ericperriard** [comment]
So far I cannot replicate the error.

Could you please print the output of  `pip3 show tensorflow`?
Also, what is your version of python?

**Comment by natelee100** [comment]
I'm running Python 3.7.4

Name: tensorflow
Version: 2.1.0
Location: \anaconda3\lib\site-packages
Requires: termcolor, gast, tensorflow-estimator, keras-preprocessing, wrapt, six, protobuf, wheel, opt-einsum, absl-py, keras-applications, scipy, tensorboard, grpcio, numpy, astor, google-pasta
Required-by: scrappybara

**Comment by ericperriard** [comment]
This is not the latest version of tensorflow.
Could you please run `pip3 install --upgrade tensorflow`, then print again `pip3 show tensorflow`... 

You should see Version **2.3.1**

**Comment by natelee100** [comment]
Perfect. Looks like it works. Thanks.
