### ISSUE TITLE
Downloading resources error

### ISSUE THREAD

**Issue by Lostincodes** [ericperriard/scrappybara#58]
Hi!
When I try to download and setup resources, I can't go on with loading forms. That is, when I execute:
python -m scrappybara download (My python version is 3.7.3), I get a decoding issue:

`wiki_bags.bz2: 1.29GB [02:15, 9.49MB/s]
data.zip: 295MB [00:32, 9.18MB/s]
forms.bz2: 92.3MB [00:09, 9.29MB/s]
Unzipping data file...
Loading entities into DB: 2941368it [35:08, 1394.90it/s]
Loading forms into DB:   0%|                                                                            | 5160/8542012 [00:00<11:26, 12433.81it/s] Traceback (most recent call last):
  File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\site-packages\scrappybara\__main__.py", line 27, in <module>
    commands[command](*sys.argv[1:])
  File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\site-packages\scrappybara\cli\download.py", line 42, in download
    setup('prd')  # deletes *.bz2 files
  File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\site-packages\scrappybara\cli\setup.py", line 32, in setup
    for line in tqdm(data, total=constants['total_forms'], desc='Loading forms into DB'):
  File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\site-packages\tqdm\std.py", line 1193, in __iter__
    for obj in iterable:
  File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6852: character maps to <undefined>`
Thanks!

**Comment by ericperriard** [comment]
(just for my information)

wiki_bags.bz2: 1.29GB [02:15, 9.49MB/s] 
data.zip: 295MB [00:32, 9.18MB/s] 
forms.bz2: 92.3MB [00:09, 9.29MB/s] 

Unzipping data file... 
Loading entities into DB: 2941368it [35:08, 1394.90it/s] 
Loading forms into DB: 0%| | 5160/8542012 [00:00<11:26, 12433.81it/s] 

Traceback (most recent call last): 

File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\runpy.py", 
line 193, in _run_module_as_main "__main__", mod_spec) 

File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\runpy.py", 
line 85, in _run_code exec(code, run_globals) 

File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\site-packages\scrappybara\__main__.py", 
line 27, in <module> commands[command](*sys.argv[1:])

File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\site-packages\scrappybara\cli\download.py", 
line 42, in download 
setup('prd') # deletes *.bz2 files 

File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\site-packages\scrappybara\cli\setup.py", 
line 32, in setup 
for line in tqdm(data, total=constants['total_forms'], desc='Loading forms into DB'): 

File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\site-packages\tqdm\std.py", 
line 1193, in __iter__ 
for obj in iterable:

File "C:\Users\plostera\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", 
line 23, in decode 
return codecs.charmap_decode(input,self.errors,decoding_table)[0] 

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6852: character maps to <undefined>

**Comment by ericperriard** [comment]
It seem it's an encoding issue.

I've uploaded a patch.

Could you please upgrade?

`pip install --upgrade scrappybara`

then download again:

`python -m scrappybara download`

It's going to take the same time, thanks for your patience!

**Comment by ericperriard** [comment]
New version has been released, closing the issue.
